//
// Created by dominik on 16.11.22.
//
#include "gtest/gtest.h"
#include "gmock/gmock.h"
#include "../src/inputReader/ParticleGenerator.h"

/**
 * @brief test if particles generated by the ParticleGenerator are at the right position
 */
TEST(CuboidGeneratorTest, GenerationTest){
    ParticleGenerator<ParticleContainer> cg;
    std::shared_ptr<ParticleContainer> par = std::make_shared<ParticleContainer>();
    std::array<double, 3> x ={0.,0.,0.};
    std::array<int, 3> n = {2,2,1};
    double h = 1.;
    double m = 1.;
    std::array<double, 3> v = {0.,0.,0.};

    cg.generateCuboid(par,x,n,h,m,v);
    std::array<double, 3> pos{};
    EXPECT_THAT((*par)[0].getX(), testing::Pointwise(testing::DoubleEq(), pos));
    pos={0., 1., 0.};
    EXPECT_THAT((*par)[1].getX(), testing::Pointwise(testing::DoubleEq(), pos));
    pos={1., 0., 0.};
    EXPECT_THAT((*par)[2].getX(), testing::Pointwise(testing::DoubleEq(), pos));
    pos={1., 1., 0.};
    EXPECT_THAT((*par)[3].getX(), testing::Pointwise(testing::DoubleEq(), pos));
}