// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "cuboid-pskel.h"

// cuboid_pskel
//

void cuboid_pskel::
x_parser (::xml_schema::double_pskel& p)
{
  this->x_parser_ = &p;
}

void cuboid_pskel::
n_parser (::xml_schema::int_pskel& p)
{
  this->n_parser_ = &p;
}

void cuboid_pskel::
h_parser (::xml_schema::double_pskel& p)
{
  this->h_parser_ = &p;
}

void cuboid_pskel::
m_parser (::xml_schema::double_pskel& p)
{
  this->m_parser_ = &p;
}

void cuboid_pskel::
v_parser (::xml_schema::double_pskel& p)
{
  this->v_parser_ = &p;
}

void cuboid_pskel::
parsers (::xml_schema::double_pskel& x,
         ::xml_schema::int_pskel& n,
         ::xml_schema::double_pskel& h,
         ::xml_schema::double_pskel& m,
         ::xml_schema::double_pskel& v)
{
  this->x_parser_ = &x;
  this->n_parser_ = &n;
  this->h_parser_ = &h;
  this->m_parser_ = &m;
  this->v_parser_ = &v;
}

cuboid_pskel::
cuboid_pskel ()
: x_parser_ (0),
  n_parser_ (0),
  h_parser_ (0),
  m_parser_ (0),
  v_parser_ (0)
{
}

// simulation_pskel
//

void simulation_pskel::
t_end_parser (::xml_schema::double_pskel& p)
{
  this->t_end_parser_ = &p;
}

void simulation_pskel::
delta_t_parser (::xml_schema::double_pskel& p)
{
  this->delta_t_parser_ = &p;
}

void simulation_pskel::
parsers (::xml_schema::double_pskel& t_end,
         ::xml_schema::double_pskel& delta_t)
{
  this->t_end_parser_ = &t_end;
  this->delta_t_parser_ = &delta_t;
}

simulation_pskel::
simulation_pskel ()
: t_end_parser_ (0),
  delta_t_parser_ (0)
{
}

// output_pskel
//

void output_pskel::
name_parser (::xml_schema::string_pskel& p)
{
  this->name_parser_ = &p;
}

void output_pskel::
frequency_parser (::xml_schema::double_pskel& p)
{
  this->frequency_parser_ = &p;
}

void output_pskel::
parsers (::xml_schema::string_pskel& name,
         ::xml_schema::double_pskel& frequency)
{
  this->name_parser_ = &name;
  this->frequency_parser_ = &frequency;
}

output_pskel::
output_pskel ()
: name_parser_ (0),
  frequency_parser_ (0)
{
}

// input_pskel
//

void input_pskel::
path_parser (::xml_schema::string_pskel& p)
{
  this->path_parser_ = &p;
}

void input_pskel::
parsers (::xml_schema::string_pskel& path)
{
  this->path_parser_ = &path;
}

input_pskel::
input_pskel ()
: path_parser_ (0)
{
}

// cuboid_pskel
//

void cuboid_pskel::
x (double)
{
}

void cuboid_pskel::
n (int)
{
}

void cuboid_pskel::
h (double)
{
}

void cuboid_pskel::
m (double)
{
}

void cuboid_pskel::
v (double)
{
}

void cuboid_pskel::
post_cuboid ()
{
}

bool cuboid_pskel::
_start_element_impl (const ::xml_schema::ro_string& ns,
                     const ::xml_schema::ro_string& n,
                     const ::xml_schema::ro_string* t)
{
  XSD_UNUSED (t);

  if (this->::xml_schema::complex_content::_start_element_impl (ns, n, t))
    return true;

  if (n == "x" && ns.empty ())
  {
    this->::xml_schema::complex_content::context_.top ().parser_ = this->x_parser_;

    if (this->x_parser_)
      this->x_parser_->pre ();

    return true;
  }

  if (n == "n" && ns.empty ())
  {
    this->::xml_schema::complex_content::context_.top ().parser_ = this->n_parser_;

    if (this->n_parser_)
      this->n_parser_->pre ();

    return true;
  }

  if (n == "h" && ns.empty ())
  {
    this->::xml_schema::complex_content::context_.top ().parser_ = this->h_parser_;

    if (this->h_parser_)
      this->h_parser_->pre ();

    return true;
  }

  if (n == "m" && ns.empty ())
  {
    this->::xml_schema::complex_content::context_.top ().parser_ = this->m_parser_;

    if (this->m_parser_)
      this->m_parser_->pre ();

    return true;
  }

  if (n == "v" && ns.empty ())
  {
    this->::xml_schema::complex_content::context_.top ().parser_ = this->v_parser_;

    if (this->v_parser_)
      this->v_parser_->pre ();

    return true;
  }

  return false;
}

bool cuboid_pskel::
_end_element_impl (const ::xml_schema::ro_string& ns,
                   const ::xml_schema::ro_string& n)
{
  if (this->::xml_schema::complex_content::_end_element_impl (ns, n))
    return true;

  if (n == "x" && ns.empty ())
  {
    if (this->x_parser_)
      this->x (this->x_parser_->post_double ());

    return true;
  }

  if (n == "n" && ns.empty ())
  {
    if (this->n_parser_)
      this->n (this->n_parser_->post_int ());

    return true;
  }

  if (n == "h" && ns.empty ())
  {
    if (this->h_parser_)
      this->h (this->h_parser_->post_double ());

    return true;
  }

  if (n == "m" && ns.empty ())
  {
    if (this->m_parser_)
      this->m (this->m_parser_->post_double ());

    return true;
  }

  if (n == "v" && ns.empty ())
  {
    if (this->v_parser_)
      this->v (this->v_parser_->post_double ());

    return true;
  }

  return false;
}

// simulation_pskel
//

void simulation_pskel::
t_end (double)
{
}

void simulation_pskel::
delta_t (double)
{
}

std::vector<double> simulation_pskel::
post_simulation ()
{
}

bool simulation_pskel::
_start_element_impl (const ::xml_schema::ro_string& ns,
                     const ::xml_schema::ro_string& n,
                     const ::xml_schema::ro_string* t)
{
  XSD_UNUSED (t);

  if (this->::xml_schema::complex_content::_start_element_impl (ns, n, t))
    return true;

  if (n == "t_end" && ns.empty ())
  {
    this->::xml_schema::complex_content::context_.top ().parser_ = this->t_end_parser_;

    if (this->t_end_parser_)
      this->t_end_parser_->pre ();

    return true;
  }

  if (n == "delta_t" && ns.empty ())
  {
    this->::xml_schema::complex_content::context_.top ().parser_ = this->delta_t_parser_;

    if (this->delta_t_parser_)
      this->delta_t_parser_->pre ();

    return true;
  }

  return false;
}

bool simulation_pskel::
_end_element_impl (const ::xml_schema::ro_string& ns,
                   const ::xml_schema::ro_string& n)
{
  if (this->::xml_schema::complex_content::_end_element_impl (ns, n))
    return true;

  if (n == "t_end" && ns.empty ())
  {
    if (this->t_end_parser_)
      this->t_end (this->t_end_parser_->post_double ());

    return true;
  }

  if (n == "delta_t" && ns.empty ())
  {
    if (this->delta_t_parser_)
      this->delta_t (this->delta_t_parser_->post_double ());

    return true;
  }

  return false;
}

// output_pskel
//

void output_pskel::
name (const ::std::string&)
{
}

void output_pskel::
frequency (double)
{
}

std::vector<std::string> output_pskel::
post_output ()
{
}

bool output_pskel::
_start_element_impl (const ::xml_schema::ro_string& ns,
                     const ::xml_schema::ro_string& n,
                     const ::xml_schema::ro_string* t)
{
  XSD_UNUSED (t);

  if (this->::xml_schema::complex_content::_start_element_impl (ns, n, t))
    return true;

  if (n == "name" && ns.empty ())
  {
    this->::xml_schema::complex_content::context_.top ().parser_ = this->name_parser_;

    if (this->name_parser_)
      this->name_parser_->pre ();

    return true;
  }

  if (n == "frequency" && ns.empty ())
  {
    this->::xml_schema::complex_content::context_.top ().parser_ = this->frequency_parser_;

    if (this->frequency_parser_)
      this->frequency_parser_->pre ();

    return true;
  }

  return false;
}

bool output_pskel::
_end_element_impl (const ::xml_schema::ro_string& ns,
                   const ::xml_schema::ro_string& n)
{
  if (this->::xml_schema::complex_content::_end_element_impl (ns, n))
    return true;

  if (n == "name" && ns.empty ())
  {
    if (this->name_parser_)
      this->name (this->name_parser_->post_string ());

    return true;
  }

  if (n == "frequency" && ns.empty ())
  {
    if (this->frequency_parser_)
      this->frequency (this->frequency_parser_->post_double ());

    return true;
  }

  return false;
}

// boundaries_pskel
//

void boundaries_pskel::
post_boundaries ()
{
}

// input_pskel
//

void input_pskel::
path (const ::std::string&)
{
}

std::string input_pskel::
post_input ()
{
}

bool input_pskel::
_start_element_impl (const ::xml_schema::ro_string& ns,
                     const ::xml_schema::ro_string& n,
                     const ::xml_schema::ro_string* t)
{
  XSD_UNUSED (t);

  if (this->::xml_schema::complex_content::_start_element_impl (ns, n, t))
    return true;

  if (n == "path" && ns.empty ())
  {
    this->::xml_schema::complex_content::context_.top ().parser_ = this->path_parser_;

    if (this->path_parser_)
      this->path_parser_->pre ();

    return true;
  }

  return false;
}

bool input_pskel::
_end_element_impl (const ::xml_schema::ro_string& ns,
                   const ::xml_schema::ro_string& n)
{
  if (this->::xml_schema::complex_content::_end_element_impl (ns, n))
    return true;

  if (n == "path" && ns.empty ())
  {
    if (this->path_parser_)
      this->path (this->path_parser_->post_string ());

    return true;
  }

  return false;
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

